# Generated by Django 3.0.3 on 2021-02-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='URL',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
