# Generated by Django 3.0.3 on 2021-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meme_app', '0003_auto_20210209_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='vips', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='URL',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='vips.jpg', upload_to='meme/images/'),
            preserve_default=False,
        ),
    ]
