# Generated by Django 3.0.3 on 2021-02-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meme_app', '0004_auto_20210209_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='meme/images/'),
        ),
    ]
