# Generated by Django 3.0.3 on 2021-02-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meme_app', '0005_auto_20210209_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='URL',
        ),
    ]
