# Generated by Django 3.0.3 on 2021-02-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meme_app', '0011_auto_20210212_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='URL',
            new_name='url',
        ),
    ]
